# GPS configuration for ASUS ROG Phone 7 (SM8550)
# Copyright (C) 2024 OmniROM Project

NTP_SERVER=pool.ntp.org
XTRA_SERVER_1=https://xtrapath1.izatcloud.net/xtra3grc.bin
XTRA_SERVER_2=https://xtrapath2.izatcloud.net/xtra3grc.bin
XTRA_SERVER_3=https://xtrapath3.izatcloud.net/xtra3grc.bin

# Error estimate
ERR_ESTIMATE=0

# Debugging
DEBUG_LEVEL=2

# Intermediate position report
INTERMEDIATE_POS=1

# Accuracy threshold
ACCURACY_THRES=5000

# Report NMEA position
NMEA_PROVIDER=0

# GPS capabilities
CAPABILITIES=0x37

# LTE positioning profile
LPP_PROFILE=3

# A-GLONASS positioning protocol
A_GLONASS_POS_PROTOCOL_SELECT=0

# Emergency SUPL
USE_EMERGENCY_PDN_FOR_EMERGENCY_SUPL=1

# GPS lock
GPS_LOCK=0

# Positioning mode
SUPL_MODE=1
SUPL_HOST=NONE
SUPL_PORT=7275
SUPL_VER=0x20000
SUPL_ES=0

# LPPe Control Plane
LPPe_CP_TECHNOLOGY=0
LPPe_UP_TECHNOLOGY=0

# NMEA Reporting Rate
NMEA_REPORT_RATE=1

# Enable/Disable sensors
SENSOR_CONTROL_MODE=1
SENSOR_USAGE=1
SENSOR_ALGORITHM_CONFIG_MASK=0x3
SENSOR_PROVIDER=1
SENSOR_ACCURACY=1

# Indoor positioning
INDOOR_POSITIONING=1