#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: 2024-2025 The OmniROM Project
# SPDX-License-Identifier: Apache-2.0
#
"""
Regenerate the stock-firmware derived files of this device tree from an
extracted stock ASUS_AI2205 firmware dump.

The dump directory has to contain the extracted partitions, e.g. the
output of `payload-dumper` + mounting/unpacking the images:

    <dump>/vendor/...           (required)
    <dump>/odm/...              (optional)
    <dump>/vendor_dlkm.img      (optional, raw image from payload.bin)
    <dump>/system_dlkm.img      (optional, raw image from payload.bin)

Generated/updated files:

    proprietary-files.txt                     every vendor/odm blob except
                                              the ones built from source
    vintf/manifest.xml                        stock device manifest
    vintf/framework_compatibility_matrix.xml  matrix entries for the
                                              non-AOSP HALs of the manifest
    vendor.prop / odm.prop                    stock vendor/odm properties
    prebuilt/kernel/images/*_dlkm.img         stock dlkm images
"""

import argparse
import os
import re
import shutil
import sys
import xml.etree.ElementTree as ET

DEVICE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Files that are generated by the build system or built from source and
# therefore must not be taken from the stock firmware.
EXCLUDE_PATTERNS = [
    # Generated by the build
    r'^(vendor|odm)/build\.prop$',
    r'^(vendor|odm)/etc/build\.prop$',
    r'^(vendor|odm)/etc/(fs_config_dirs|fs_config_files|group|passwd)$',
    r'^(vendor|odm)/etc/linker\.config\.pb$',
    r'^(vendor|odm)/etc/NOTICE\.xml\.gz$',
    r'^(vendor|odm)/etc/selinux/',
    r'^(vendor|odm)/etc/vintf/manifest\.xml$',
    r'^(vendor|odm)/etc/vintf/compatibility_matrix\.xml$',
    r'^(vendor|odm)/lost\+found/',
    r'^(vendor|odm)/.*\.(odex|vdex|art|prof)$',
    r'^(vendor|odm)/.*/oat/',
    r'^vendor/etc/fstab\.qcom$',
    r'^vendor/lib/modules/',
    r'^vendor/lib64/modules/',
    # Built from source (see device.mk)
    r'^vendor/bin/vndservicemanager$',
    r'^vendor/etc/init/vndservicemanager\.rc$',
    r'^vendor/bin/hw/android\.hardware\.boot',
    r'^vendor/etc/init/android\.hardware\.boot',
    r'^vendor/etc/vintf/manifest/android\.hardware\.boot',
    r'^vendor/lib(64)?/hw/android\.hardware\.boot@',
    r'^vendor/lib(64)?/hw/bootctrl\.',
    r'^vendor/overlay/AI2205',
    # Mount points / symlinks created by the build
    r'^vendor/(asusfw|xrom|bt_firmware|dsp|firmware_mnt|vm-system)(/|$)',
]

MANIFEST_HEADER = '''<!--
    Device manifest taken from the stock ASUS_AI2205 vendor
    (/vendor/etc/vintf/manifest.xml). HALs that ship their own
    VINTF fragment in /vendor/etc/vintf/manifest/ are not listed here.
    Refresh it from a stock dump with tools/generate-from-dump.py.
-->
'''

MATRIX_HEADER = '''<!--
    Framework compatibility matrix entries for the non-AOSP HALs of the
    stock device manifest that are not covered by
    hardware/qcom-caf/common/vendor_framework_compatibility_matrix.xml.
    Generated by tools/generate-from-dump.py.
-->
'''

# Properties which are generated by the build system itself
PROP_EXCLUDE = re.compile(
    r'^(import |ro\.build\.|ro\.(vendor|odm)\.build\.|ro\.product\.|'
    r'ro\.(vendor|odm)\.product\.|ro\.bootimage\.|ro\.board\.|ro\.vndk\.|'
    r'ro\.(vendor|odm)\.api_level|ro\.vendor\.redirect_socket_calls|'
    r'ro\.(vendor|odm)\.dlkm\.|ro\.(vendor|odm)\.security_patch)'
)

GENERATED_PROPS_MARKER = '# ---- Generated by tools/generate-from-dump.py ----'


def excluded(rel_path):
    return any(re.search(p, rel_path) for p in EXCLUDE_PATTERNS)


def list_blobs(dump, partition):
    root = os.path.join(dump, partition)
    blobs = []
    if not os.path.isdir(root):
        return blobs
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for name in sorted(filenames):
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, dump).replace(os.sep, '/')
            if os.path.islink(full) or excluded(rel):
                continue
            blobs.append(rel)
    return blobs


def write_proprietary_files(dump):
    blobs = list_blobs(dump, 'vendor') + list_blobs(dump, 'odm')
    if not blobs:
        sys.exit(f'error: no vendor files found in {dump}/vendor')

    out = [
        '# All files are taken from the stock ASUS_AI2205 firmware.',
        '# Generated by tools/generate-from-dump.py, do not edit by hand.',
    ]
    section = None
    for blob in blobs:
        parts = blob.split('/')
        new_section = '/'.join(parts[:2]) if len(parts) > 2 else parts[0]
        if new_section != section:
            section = new_section
            out.append('')
            out.append(f'# {section}')
        out.append(blob)

    with open(os.path.join(DEVICE_DIR, 'proprietary-files.txt'), 'w') as f:
        f.write('\n'.join(out) + '\n')
    print(f'proprietary-files.txt: {len(blobs)} files')


def hal_groups(hal):
    """Return {version: {interface: [instances]}} for a manifest <hal>."""
    groups = {}
    for version in hal.findall('version'):
        for iface in hal.findall('interface'):
            for inst in iface.findall('instance'):
                groups.setdefault(version.text, {}).setdefault(
                    iface.findtext('name'), []).append(inst.text)
    if hal.get('format') == 'aidl' and not hal.findall('version'):
        for iface in hal.findall('interface'):
            for inst in iface.findall('instance'):
                groups.setdefault(None, {}).setdefault(
                    iface.findtext('name'), []).append(inst.text)
    for fqname in hal.findall('fqname'):
        m = re.match(r'(?:@([\d.]+)::)?(\w+)/(.+)', fqname.text.strip())
        version, iface, inst = m.groups()
        insts = groups.setdefault(version, {}).setdefault(iface, [])
        if inst not in insts:
            insts.append(inst)
    return groups


def write_manifest(dump):
    src = os.path.join(dump, 'vendor/etc/vintf/manifest.xml')
    if not os.path.isfile(src):
        print('warning: stock vendor manifest not found, keeping vintf/manifest.xml')
        return None

    root = ET.parse(src).getroot()
    out = [f'<manifest version="{root.get("version")}" type="device" '
           f'target-level="{root.get("target-level")}">']
    hals = []
    for hal in root.findall('hal'):
        name = hal.findtext('name')
        fmt = hal.get('format', 'hidl')
        transport = hal.findtext('transport')
        for version, ifaces in hal_groups(hal).items():
            hals.append((fmt, name, version, ifaces))
            out.append(f'    <hal format="{fmt}">')
            out.append(f'        <name>{name}</name>')
            if transport:
                out.append(f'        <transport>{transport}</transport>')
            if version:
                out.append(f'        <version>{version}</version>')
            for iface, insts in ifaces.items():
                out.append('        <interface>')
                out.append(f'            <name>{iface}</name>')
                for inst in insts:
                    out.append(f'            <instance>{inst}</instance>')
                out.append('        </interface>')
            out.append('    </hal>')
    out.append('</manifest>')

    with open(os.path.join(DEVICE_DIR, 'vintf/manifest.xml'), 'w') as f:
        f.write(MANIFEST_HEADER + '\n'.join(out) + '\n')
    print(f'vintf/manifest.xml: {len(hals)} HALs')
    return hals


def read_manifest_hals():
    root = ET.parse(os.path.join(DEVICE_DIR, 'vintf/manifest.xml')).getroot()
    hals = []
    for hal in root.findall('hal'):
        for version, ifaces in hal_groups(hal).items():
            hals.append((hal.get('format', 'hidl'), hal.findtext('name'),
                         version, ifaces))
    return hals


def write_matrix(hals, android_root):
    covered = set()
    qcom_matrix = os.path.join(
        android_root,
        'hardware/qcom-caf/common/vendor_framework_compatibility_matrix.xml')
    if os.path.isfile(qcom_matrix):
        for hal in ET.parse(qcom_matrix).getroot().findall('hal'):
            covered.add(hal.findtext('name'))
    else:
        print(f'warning: {qcom_matrix} not found, listing all vendor HALs')

    out = ['<compatibility-matrix version="2.0" type="framework">']
    count = 0
    for fmt, name, version, ifaces in hals:
        if name.startswith('android.') or name in covered:
            continue
        count += 1
        out.append(f'    <hal format="{fmt}" optional="true">')
        out.append(f'        <name>{name}</name>')
        if version and fmt == 'hidl':
            out.append(f'        <version>{version}</version>')
        for iface, insts in ifaces.items():
            out.append('        <interface>')
            out.append(f'            <name>{iface}</name>')
            for inst in insts:
                out.append(f'            <instance>{inst}</instance>')
            out.append('        </interface>')
        out.append('    </hal>')
    out.append('</compatibility-matrix>')

    with open(os.path.join(DEVICE_DIR,
                           'vintf/framework_compatibility_matrix.xml'), 'w') as f:
        f.write(MATRIX_HEADER + '\n'.join(out) + '\n')
    print(f'vintf/framework_compatibility_matrix.xml: {count} HALs')


def write_props(dump, partition, prop_file, candidates):
    src = next((os.path.join(dump, c) for c in candidates
                if os.path.isfile(os.path.join(dump, c))), None)
    dst = os.path.join(DEVICE_DIR, prop_file)
    if src is None:
        print(f'warning: no stock {partition} build.prop found, keeping {prop_file}')
        return

    props = []
    seen = set()
    with open(src, errors='replace') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            if PROP_EXCLUDE.match(line):
                continue
            key = line.split('=', 1)[0]
            if key in seen:
                props = [p for p in props if p.split('=', 1)[0] != key]
            seen.add(key)
            props.append(line)

    manual = ''
    if os.path.isfile(dst):
        with open(dst) as f:
            manual = f.read().split(GENERATED_PROPS_MARKER)[0].rstrip() + '\n\n'
    with open(dst, 'w') as f:
        f.write(manual + GENERATED_PROPS_MARKER + '\n')
        f.write(f'# from stock /{os.path.relpath(src, dump)}\n')
        f.write('\n'.join(props) + '\n')
    print(f'{prop_file}: {len(props)} properties')


def copy_dlkm_images(dump):
    dst_dir = os.path.join(DEVICE_DIR, 'prebuilt/kernel/images')
    for image in ('vendor_dlkm.img', 'system_dlkm.img'):
        for candidate in (image, os.path.join('images', image)):
            src = os.path.join(dump, candidate)
            if os.path.isfile(src):
                os.makedirs(dst_dir, exist_ok=True)
                shutil.copyfile(src, os.path.join(dst_dir, image))
                print(f'prebuilt/kernel/images/{image}: copied')
                break
        else:
            print(f'warning: {image} not found in dump')


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('dump', help='extracted stock firmware directory')
    parser.add_argument('--android-root',
                        default=os.path.join(DEVICE_DIR, '../../..'),
                        help='root of the OmniROM source tree')
    args = parser.parse_args()

    dump = os.path.abspath(args.dump)
    if not os.path.isdir(os.path.join(dump, 'vendor')):
        sys.exit(f'error: {dump}/vendor does not exist')

    write_proprietary_files(dump)
    hals = write_manifest(dump) or read_manifest_hals()
    write_matrix(hals, os.path.abspath(args.android_root))
    write_props(dump, 'vendor', 'vendor.prop', ['vendor/build.prop'])
    write_props(dump, 'odm', 'odm.prop', ['odm/etc/build.prop', 'odm/build.prop'])
    copy_dlkm_images(dump)


if __name__ == '__main__':
    main()
